# Generated by Django 3.1.1 on 2020-09-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('SEOUL', 'Seoul'), ('GYENGGI', 'Gyeonggi'), ('INCHEON', 'Incheon')], default='SEOUL', help_text='지역', max_length=20)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('sub_info', models.CharField(default='', max_length=100)),
                ('detail_info', models.CharField(default='', max_length=100)),
                ('type', models.CharField(choices=[('지하', 'A Type'), ('지상', 'B Type'), ('기계식', 'C Type')], default='지상', help_text='주차장타입', max_length=10)),
                ('operating_time', models.CharField(choices=[('24시간', 'A Time'), ('06:00 ~ 23:59', 'B Time'), ('07:00 ~ 23:59', 'C Time'), ('05:30 ~ 23:59', 'D Time')], default='24시간', help_text='운영시간', max_length=20)),
            ],
        ),
    ]
