# Generated by Django 3.1 on 2020-08-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(default='seoul', max_length=20)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('detail_info', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
