# Generated by Django 3.1 on 2020-08-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carzone',
            name='blog_page',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='carzone',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]