# Generated by Django 3.1.1 on 2020-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carzone',
            name='image',
            field=models.ImageField(null=True, upload_to='CarZoneImages/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='carzone',
            name='operating_time',
            field=models.CharField(choices=[('24시간', '24시간'), ('06:00 ~ 23:59', '06:00 ~ 23:59'), ('07:00 ~ 23:59', '07:00 ~ 23:59'), ('05:30 ~ 23:59', '05:30 ~ 23:59')], default='24시간', help_text='운영시간', max_length=20),
        ),
        migrations.AlterField(
            model_name='carzone',
            name='region',
            field=models.CharField(choices=[('SEOUL', '서울'), ('GYENGGI', '경기도'), ('INCHEON', '인천')], default='SEOUL', help_text='지역', max_length=20),
        ),
        migrations.AlterField(
            model_name='carzone',
            name='type',
            field=models.CharField(choices=[('지하', '지하'), ('지상', '지상'), ('기계식', '기계식')], default='지상', help_text='주차장타입', max_length=10),
        ),
    ]
