# Generated by Django 3.1.1 on 2020-09-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzones', '0002_auto_20200912_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carzone',
            name='operating_time',
            field=models.CharField(choices=[('24시간', 'A Time'), ('06:00 ~ 23:59', 'B Time'), ('07:00 ~ 23:59', 'C Time'), ('05:30 ~ 23:59', 'D Time')], default='24시간', help_text='운영시간', max_length=20),
        ),
        migrations.AlterField(
            model_name='carzone',
            name='region',
            field=models.CharField(choices=[('SEOUL', 'Seoul'), ('GYENGGI', 'Gyeonggi'), ('INCHEON', 'Incheon')], default='SEOUL', help_text='지역', max_length=20),
        ),
        migrations.AlterField(
            model_name='carzone',
            name='type',
            field=models.CharField(choices=[('지하', 'A Type'), ('지상', 'B Type'), ('기계식', 'C Type')], default='지상', help_text='주차장타입', max_length=10),
        ),
    ]
