# Generated by Django 3.1 on 2020-08-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carzones', '0002_auto_20200827_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carzone',
            name='blog_page',
        ),
    ]