# Generated by Django 3.1 on 2020-08-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzones', '0004_carzone_operating_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='carzone',
            name='sub_info',
            field=models.CharField(default='', max_length=100),
        ),
    ]
