# Generated by Django 3.1 on 2020-08-31 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carzones', '0005_carzone_sub_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('manufacturer', models.CharField(max_length=20)),
                ('fuel', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('shift_type', models.CharField(max_length=10)),
                ('riding_capacity', models.PositiveIntegerField()),
                ('is_event_model', models.BooleanField()),
                ('manual_page', models.CharField(default='', max_length=100)),
                ('safety_option', models.CharField(default='', max_length=255)),
                ('convenience_option', models.CharField(default='', max_length=255)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socar_zones', to='carzones.carzone')),
            ],
        ),
    ]
