# Generated by Django 3.1.1 on 2020-09-10 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carzones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoBeforeUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ImagesBeforeUse/%Y/%m/%d')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='차 번호판', max_length=20, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('manufacturer', models.CharField(choices=[('현대자동차', 'Hyundai'), ('기아자동차', 'Kia'), ('BMW', 'Bmw'), ('쌍용자동차', 'Ssangyong'), ('르노삼성자동차', 'Rnaultsamsung'), ('벤츠', 'Benz'), ('포르쉐', 'Porsche')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('경유', 'Diesel'), ('휘발유', 'Gasoline'), ('전기', 'Electric')], default='휘발유', help_text='연료', max_length=20)),
                ('type_of_vehicle', models.CharField(choices=[('경차', 'A Segment'), ('소형', 'B Segment'), ('준중형', 'C Segment'), ('중형', 'D Segment'), ('준대형', 'E Segment'), ('대형', 'F Segment'), ('스포츠카', 'S Segment'), ('미니밴', 'M Segment'), ('SUV', 'J Segment')], default='준중형', help_text='차종', max_length=10)),
                ('shift_type', models.CharField(choices=[('자동', 'Auto'), ('수동', 'Stick')], default='자동', help_text='기어', max_length=10)),
                ('riding_capacity', models.PositiveIntegerField(help_text='승차정원')),
                ('is_event_model', models.BooleanField(help_text='쏘카세이브')),
                ('manual_page', models.CharField(default='', max_length=100)),
                ('safety_option', models.CharField(default='', max_length=255)),
                ('convenience_option', models.CharField(default='', max_length=255)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='carzones.carzone')),
            ],
        ),
    ]
