# Generated by Django 3.1.1 on 2020-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('경유', '경유'), ('휘발유', '휘발유'), ('전기', '전기')], default='휘발유', help_text='연료', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(choices=[('현대자동차', '현대자동차'), ('기아자동차', '기아자동차'), ('BMW', 'BMW'), ('쌍용자동차', '쌍용자동차'), ('르노삼성자동차', '르노삼성자동차'), ('벤츠', '벤츠'), ('포르쉐', '포르쉐')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='shift_type',
            field=models.CharField(choices=[('자동', '자동'), ('수동', '수동')], default='자동', help_text='기어', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='type_of_vehicle',
            field=models.CharField(choices=[('경차', '경차'), ('소형', '소형'), ('준중형', '준중형'), ('중형', '중형'), ('준대형', '준대형'), ('대형', '대형'), ('스포츠카', '스포츠카'), ('미니밴', '미니밴'), ('SUV', 'SUV')], default='준중형', help_text='차종', max_length=10),
        ),
        migrations.AlterField(
            model_name='photobeforeuse',
            name='image',
            field=models.ImageField(null=True, upload_to='ImagesBeforeUse/%Y/%m/%d'),
        ),
    ]
