# Generated by Django 3.1.1 on 2020-09-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carzones', '0001_initial'),
        ('cars', '0002_cartimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartimetable',
            name='zone',
            field=models.ForeignKey(default=260, on_delete=django.db.models.deletion.CASCADE, related_name='time_tables', to='carzones.carzone'),
            preserve_default=False,
        ),
    ]
