# Generated by Django 3.1.1 on 2020-09-13 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200911_1350'),
        ('cars', '0002_auto_20200912_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobeforeuse',
            name='reservation',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='ready_photos', to='reservations.reservation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photobeforeuse',
            name='image',
            field=models.ImageField(null=True, upload_to='ImagesBeforeUse/%Y/%m/%d/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
