# Generated by Django 3.1.1 on 2020-09-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20200913_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobeforeuse',
            name='image',
            field=models.ImageField(null=True, upload_to='ImagesBeforeUse/%Y/%m/%d/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
