# Generated by Django 3.1.1 on 2020-09-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20200913_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('경유', 'Diesel'), ('휘발유', 'Gasoline'), ('전기', 'Electric')], default='휘발유', help_text='연료', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='CarImages/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(choices=[('현대자동차', 'Hyundai'), ('기아자동차', 'Kia'), ('BMW', 'Bmw'), ('쌍용자동차', 'Ssangyong'), ('르노삼성자동차', 'Rnaultsamsung'), ('벤츠', 'Benz'), ('포르쉐', 'Porsche'), ('쉐보레', 'Chevrolet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='shift_type',
            field=models.CharField(choices=[('자동', 'Auto'), ('수동', 'Stick')], default='자동', help_text='기어', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='type_of_vehicle',
            field=models.CharField(choices=[('경차', 'A Segment'), ('소형', 'B Segment'), ('준중형', 'C Segment'), ('중형', 'D Segment'), ('준대형', 'E Segment'), ('대형', 'F Segment'), ('스포츠카', 'S Segment'), ('미니밴', 'M Segment'), ('SUV', 'J Segment')], default='준중형', help_text='차종', max_length=10),
        ),
    ]
