# Generated by Django 3.1.1 on 2020-09-28 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carzones', '0001_initial'),
        ('cars', '0003_cartimetable_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.CharField(choices=[('special', '스페셜'), ('standard', '스탠다드'), ('light', '라이트')], default='light', help_text='차량손해면책상품', max_length=30)),
                ('date_time_start', models.DateTimeField(help_text='예약시작날짜시간')),
                ('date_time_end', models.DateTimeField(help_text='예약종료날짜시간')),
                ('date_time_extension', models.DateTimeField(help_text='연장종료날짜시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='TimeStamp')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_cars', to='cars.car')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_members', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_zones', to='carzones.carzone')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_paid', '결제전'), ('paid_1', '운행전결제완료'), ('paid_2', '운행후결제완료'), ('using', '사용중'), ('extended', '사용중추가연장'), ('finished', '반납완료')], default='not_paid', help_text='대여진행상태', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='TimeStamp')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='reservations.reservation')),
            ],
        ),
    ]
