# Generated by Django 3.1.1 on 2020-09-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='insurance',
            field=models.CharField(choices=[('special', 'special'), ('standard', 'standard'), ('light', 'light'), ('none', 'none')], max_length=40),
        ),
    ]
