# Generated by Django 3.1.1 on 2020-10-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_time_extension',
            field=models.DateTimeField(help_text='연장종료날짜시간', null=True),
        ),
    ]
