# Generated by Django 3.1.1 on 2020-09-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200911_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='insurance',
            field=models.CharField(choices=[('special', 'Special'), ('standard', 'Standard'), ('light', 'Light'), ('none', 'None')], default='none', max_length=40),
        ),
    ]
