# Generated by Django 3.1.1 on 2020-10-06 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0002_auto_20201001_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoBeforeUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='ImagesBeforeUse/%Y/%m/%d/<django.db.models.fields.related.ForeignKey>/')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_owners', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_photos', to='reservations.reservation')),
            ],
        ),
    ]
