# Generated by Django 3.1 on 2020-09-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit_point',
            field=models.IntegerField(default=100000),
        ),
    ]
