# Generated by Django 3.1.1 on 2020-10-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default='01012345678', max_length=11),
            preserve_default=False,
        ),
    ]
