# Generated by Django 3.1.1 on 2020-10-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
