# Generated by Django 3.1.1 on 2020-10-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbeforeuse',
            name='extension_fee',
            field=models.PositiveIntegerField(default=0, help_text='연장요금'),
        ),
        migrations.AlterField(
            model_name='paymentbeforeuse',
            name='etc_discount',
            field=models.PositiveIntegerField(default=0, help_text='기타할인금액'),
        ),
    ]
