# Generated by Django 3.1.1 on 2020-10-07 04:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='date_time_start',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 10, 7, 4, 48, 57, 909524, tzinfo=utc), help_text='쿠폰사용시작시간'),
            preserve_default=False,
        ),
    ]
