# Generated by Django 3.1.1 on 2020-09-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20200909_1412'),
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carprice',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carprice', to='cars.car'),
        ),
    ]
