# Generated by Django 3.1.1 on 2020-09-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carprice',
            name='weekday_price_per_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carprice',
            name='weekend_price_per_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InsuranceFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_price', models.PositiveIntegerField(default=0)),
                ('standard_price', models.PositiveIntegerField(default=0)),
                ('special_price', models.PositiveIntegerField(default=0)),
                ('light_price_per_min', models.PositiveIntegerField(default=0)),
                ('standard_price_per_min', models.PositiveIntegerField(default=0)),
                ('special_price_per_min', models.PositiveIntegerField(default=0)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_fees', to='cars.car')),
            ],
        ),
    ]
