# Generated by Django 3.1.1 on 2020-09-26 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_cartimetable'),
        ('prices', '0003_auto_20200925_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancefee',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='cars.car'),
        ),
    ]
